import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // --- FRONTEND SIDEBAR ---
  frontendSidebar: [
    {
      type: "autogenerated",
      dirName: "frontend",
    },
  ],

  // --- API SIDEBAR ---
  apiSidebar: [
    {
      type: "category",
      label: "Habits API",
      items: [
        {
          type: "autogenerated",
          dirName: "api/habits",
        },
      ],
    },
    {
      type: "category",
      label: "Tasks API",
      items: [
        {
          type: "autogenerated",
          dirName: "api/tasks",
        },
      ],
    },
    {
      type: "category",
      label: "Pomodoro API",
      items: [
        {
          type: "autogenerated",
          dirName: "api/pomodoro",
        },
      ],
    },
  ],
};

export default sidebars;
