import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "category",
      label: "🔌 Habits API",
      link: {
        type: "doc",
        id: "api/habits/habits-api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "api/habits",
        },
      ],
    },
    {
      type: "category",
      label: "✅ Tasks API",
      link: {
        type: "doc",
        id: "api/tasks/tasks-api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "api/tasks",
        },
      ],
    },
    {
      type: "category",
      label: "🍅 Pomodoro API",
      link: {
        type: "doc",
        id: "api/pomodoro/pomodoro-api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "api/pomodoro",
        },
      ],
    },
  ],
};

export default sidebars;
