openapi: 3.0.3
info:
  title: Habits API
  version: 1.0.0
  description: |
    API для управления привычками и отслеживания прогресса.
    
    **Связанные API:**
    - Pomodoro API - для отслеживания времени работы над привычками

servers:
  - url: http://localhost:8080/api/v1
    description: Development server

tags:
  - name: Habits
  - name: Completions
  - name: Statistics

components:
  schemas:
    FrequencyType:
      type: string
      enum: [daily, weekly, custom]
      example: daily

    IntensityLevel:
      type: integer
      enum: [0, 1, 2, 3, 4]
      example: 2

    Habit:
      type: object
      required: [id, userId, name, frequency, reminderEnabled, startDate, goalDays, createdAt, updatedAt]
      properties:
        id:
          type: string
          example: h1
        userId:
          type: string
          example: u1
        name:
          type: string
          maxLength: 100
          example: Morning Meditation
        description:
          type: string
          maxLength: 500
        frequency:
          $ref: '#/components/schemas/FrequencyType'
        reminderEnabled:
          type: boolean
        reminderTime:
          type: string
          format: time
          example: "07:30"
        targetDaysPerWeek:
          type: integer
          minimum: 1
          maximum: 7
        specificDays:
          type: array
          items:
            type: integer
            minimum: 1
            maximum: 7
          example: [1, 3, 5]
        startDate:
          type: string
          format: date
        goalDays:
          type: integer
          minimum: 1
        archived:
          type: boolean
          default: false
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          example: "#FFD700"
        progress:
          type: number
          format: float
          minimum: 0
          maximum: 100
          readOnly: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true

    HabitCreate:
      type: object
      required: [name, frequency, startDate, goalDays]
      properties:
        name:
          type: string
          maxLength: 100
        description:
          type: string
          maxLength: 500
        frequency:
          $ref: '#/components/schemas/FrequencyType'
        reminderEnabled:
          type: boolean
          default: false
        reminderTime:
          type: string
          format: time
        targetDaysPerWeek:
          type: integer
        specificDays:
          type: array
          items:
            type: integer
        startDate:
          type: string
          format: date
        goalDays:
          type: integer
        color:
          type: string

    HabitUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        reminderEnabled:
          type: boolean
        reminderTime:
          type: string
        color:
          type: string
        archived:
          type: boolean

    Completion:
      type: object
      required: [id, habitId, date, completed, pomodoros]
      properties:
        id:
          type: string
        habitId:
          type: string
        date:
          type: string
          format: date
        completed:
          type: boolean
        pomodoros:
          type: integer
          minimum: 0
          description: Количество завершённых pomodoro сессий
        intensity:
          $ref: '#/components/schemas/IntensityLevel'
        completedAt:
          type: string
          format: date-time
        note:
          type: string
          maxLength: 500

    CompletionCreate:
      type: object
      required: [date, completed, pomodoros]
      properties:
        date:
          type: string
          format: date
        completed:
          type: boolean
        pomodoros:
          type: integer
          minimum: 0
        intensity:
          $ref: '#/components/schemas/IntensityLevel'
        note:
          type: string

    Stats:
      type: object
      properties:
        habitId:
          type: string
        currentStreak:
          type: integer
        longestStreak:
          type: integer
        totalCompletions:
          type: integer
        totalPomodoros:
          type: integer
        averagePomodorosPerDay:
          type: number
        completionRate:
          type: number
        weeklyAverage:
          type: number
        monthlyAverage:
          type: number
        lastCompletedDate:
          type: string
          format: date

    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: string

paths:
  /habits:
    get:
      tags: [Habits]
      summary: Get all habits
      parameters:
        - name: includeArchived
          in: query
          schema:
            type: boolean
        - name: frequency
          in: query
          schema:
            $ref: '#/components/schemas/FrequencyType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Habit'
    
    post:
      tags: [Habits]
      summary: Create habit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HabitCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Habit'

  /habits/{habitId}:
    get:
      tags: [Habits]
      summary: Get habit by ID
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Habit'
    
    patch:
      tags: [Habits]
      summary: Update habit
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HabitUpdate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Habit'
    
    delete:
      tags: [Habits]
      summary: Delete habit
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted

  /habits/{habitId}/completions:
    get:
      tags: [Completions]
      summary: Get completion history
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Completion'
    
    post:
      tags: [Completions]
      summary: Mark habit as completed
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompletionCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Completion'

  /habits/{habitId}/completions/{date}:
    get:
      tags: [Completions]
      summary: Get completion by date
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Completion'
    
    delete:
      tags: [Completions]
      summary: Delete completion
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        '204':
          description: Deleted

  /habits/{habitId}/stats:
    get:
      tags: [Statistics]
      summary: Get habit statistics
      parameters:
        - name: habitId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'