openapi: 3.0.3
info:
  title: Tasks API
  version: 1.0.0
  description: |
    API для управления задачами с приоритетами и категориями.
    
    **Связанные API:**
    - Pomodoro API - для отслеживания времени работы над задачами

servers:
  - url: http://localhost:8080/api/v1
    description: Development server

tags:
  - name: Tasks

components:
  schemas:
    Priority:
      type: string
      enum: [low, medium, high]
      example: high

    TaskStatus:
      type: string
      enum: [pending, in_progress, completed, cancelled]
      example: in_progress

    Task:
      type: object
      required: [id, title, priority, status, pomodoro, createdAt, updatedAt]
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          minLength: 3
          maxLength: 200
          example: "Buy groceries"
        description:
          type: string
          maxLength: 2000
        dueDate:
          type: string
          format: date
          example: "2025-09-01"
        category:
          type: string
          example: "Personal"
        priority:
          $ref: "#/components/schemas/Priority"
        pomodoro:
          type: integer
          minimum: 0
          description: Количество завершённых pomodoro сессий
          example: 2
        status:
          $ref: "#/components/schemas/TaskStatus"
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        completedAt:
          type: string
          format: date-time
          readOnly: true

    TaskCreate:
      type: object
      required: [title, priority, pomodoro]
      properties:
        title:
          type: string
          minLength: 3
        description:
          type: string
        dueDate:
          type: string
          format: date
        category:
          type: string
        priority:
          $ref: "#/components/schemas/Priority"
        pomodoro:
          type: integer
          minimum: 0
          default: 0
        status:
          $ref: "#/components/schemas/TaskStatus"
          default: pending

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date
        category:
          type: string
        priority:
          $ref: "#/components/schemas/Priority"
        pomodoro:
          type: integer
        status:
          $ref: "#/components/schemas/TaskStatus"

    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: string

paths:
  /tasks:
    get:
      tags: [Tasks]
      summary: Get all tasks
      parameters:
        - name: status
          in: query
          schema:
            $ref: "#/components/schemas/TaskStatus"
        - name: priority
          in: query
          schema:
            $ref: "#/components/schemas/Priority"
        - name: category
          in: query
          schema:
            type: string
        - name: search
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
    
    post:
      tags: [Tasks]
      summary: Create task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskCreate"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"

  /tasks/{taskId}:
    get:
      tags: [Tasks]
      summary: Get task by ID
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    
    patch:
      tags: [Tasks]
      summary: Update task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskUpdate"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    
    delete:
      tags: [Tasks]
      summary: Delete task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Deleted